name: Release_Clang21

on:
  workflow_dispatch: # Manual trigger from the "Actions" tab

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating releases

    steps:
      - name: Download Clang Archive
        run: |
          # Downloading clang-r574158 (Current AOSP Clang-Stable)
          curl -L "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/ebcc6c3bef363bc539ea39f45b6abae1dce6ff1a/clang-r574158.tar.gz" -o clang-r574158.tar.gz
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v1.5.6" # Incremented tag version
          name: "Clang21 r574158 Stable"
          body: |
            ## AOSP Clang Prebuilt
            - **Version:** CLang 21.0.0 - r574158 (Stable)
            - **Source:** [Android Google Source](https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/mirror-goog-main-llvm-toolchain-source/README.md)
            - **Update Date:** March 2026
          files: clang-r574158.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
