name: Release_Clang

on:
  workflow_dispatch: # Manual trigger from the "Actions" tab

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating releases

    steps:
      - name: Download Clang Archive
        run: |
          curl -L "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/mirror-goog-main-llvm-toolchain-source/clang-r547379.tar.gz" -o clang-r547379.tar.gz
    
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v1.3.0"
          name: "Clang20 r547379"
          body: "Prebuilt AOSP Clang from Android Google Source."
          files: clang-r584948.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
